### ISSUE TITLE
rebar3 not installed on ubuntu 22.04

### ISSUE THREAD

**Issue by lukaszsamson** [erlef/setup-beam#163]
When running this action all builds on Ubuntu 22.04 fail due to rebar3 not being installed (or not in PATH)
https://github.com/lukaszsamson/erlzmq/blob/master/.github/workflows/ci.yml

```
name: CI

on:
  pull_request:
  push:
    branches:
      - master

jobs:
  test:
    name: test (Erlang/OTP ${{matrix.otp}}, ${{matrix.os}})
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: false
      matrix:
        os: [ubuntu-22.04, ubuntu-20.04, ubuntu-18.04]
        otp: [25.x, 24.x, 23.x]
    steps:
      - uses: actions/checkout@v3
      - uses: erlef/setup-beam@v1
        with:
          otp-version: ${{matrix.otp}}
      - name: Install Dependencies
        run: |
          sudo apt update
          sudo apt install libzmq3-dev
      - name: Build
        run: rebar3 compile
      - name: Test
        run: rebar3 eunit
      - name: Build docs
        run: rebar3 edoc
```

rebar3: command not found
https://github.com/lukaszsamson/erlzmq/actions/runs/3665132201/jobs/6196141527

It works correctly on other ubuntu versions

Expected behavior:
rebar3 should be installed by default according to action spec https://github.com/erlef/setup-beam/blob/96fce952fd41d6439cf4ad0b65c98568eb842e72/action.yml#L25
