### ISSUE TITLE
otp.tar.gz: No such file or directory

### ISSUE THREAD

**Issue by KamilLelonek** [erlef/setup-beam#185]
What could be the issue?

```shell
[test.yml/test] ⭐ Run Main Install Elixir & Erlang based on .tool-versions file
[test.yml/test]   🐳  docker cp src=/Users/kamillelonek/.cache/act/erlef-setup-beam@v1/ dst=/var/run/act/actions/erlef-setup-beam@v1/
[test.yml/test]   🐳  docker exec cmd=[node /var/run/act/actions/erlef-setup-beam@v1/dist/index.js] user= workdir=
[test.yml/test]   ❓  ##[group]Parsing version file at .tool-versions
| Consuming erlang at version 25.2.3
| Consuming elixir at version 1.14.4-otp-25
| ... done!
[test.yml/test]   ❓  ##[endgroup]
[test.yml/test]   ❓  ##[group]Installing Erlang/OTP OTP-25.2.3 - built on ubuntu-20.04
| [command]/run/act/actions/erlef-setup-beam@v1/dist/install-otp.sh ubuntu-20.04 OTP-25.2.3
| otp.tar.gz: No such file or directory
[test.yml/test]   ❗  ::error::The process '/run/act/actions/erlef-setup-beam@v1/dist/install-otp.sh' failed with exit code 1
[test.yml/test]   ❌  Failure - Main Install Elixir & Erlang based on .tool-versions file
[test.yml/test] exitcode '1': failure
[test.yml/test] 🏁  Job failed
Error: Job 'test' failed
```

The action is defined as follows:

```yaml
    - name: Install Elixir & Erlang based on .tool-versions file
      uses: erlef/setup-beam@v1
      with:
        version-file: .tool-versions
        version-type: strict
```

**Comment by paulo-ferraz-oliveira** [comment]
It seems the `wget` might have failed, though https://repo.hex.pm/builds/otp/ubuntu-20.04/OTP-25.2.3.tar.gz exists (as per your input arguments), and it would've failed earlier otherwise (if we couldn't find a reference to download).

Is this happening consistently? Is the workflow file open that we can inspect it?

Otherwise, I'd propose you create the smallest possible example to install Erlang/OTP with `.tool-versions` as you've defined. (you can also pass it to me here and I'll try in an example repo, for reference)

**Comment by KamilLelonek** [comment]
This is the entire workflow:

```yaml
on: push
env:
  MIX_ENV: test
  MAX_TEST_FAILURES: 5
jobs:
  test:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3

    - name: Install Elixir & Erlang based on .tool-versions file
      uses: erlef/setup-beam@v1
      with:
        version-file: .tool-versions
        version-type: strict
```

The problem appears only when running with [act](https://github.com/nektos/act).
