### ISSUE TITLE
Requested Erlang/OTP version (23.3) not found in version list error in github action

### ISSUE THREAD

**Issue by thomas9911** [erlef/setup-beam#187]
Got this error in my github action. 

```
Requested Erlang/OTP version (23.3) not found in version list (should you be using option 'version-type': 'strict'?)
```

github workflow file

```
jobs:
  test:
    runs-on: ubuntu-latest
    name: OTP ${{matrix.otp}} / Elixir ${{matrix.elixir}}
    strategy:
      matrix:
        otp: ["23.3", "24.3", "25.3"]
        elixir: ["1.12.3", "1.13.4", "1.14.3"]
        exclude:
          - otp: "25.3"
            elixir: "1.12.3"
    steps:
      - uses: actions/checkout@v3
      - uses: erlef/setup-beam@v1
        with:
          otp-version: ${{matrix.otp}}
          elixir-version: ${{matrix.elixir}}
      - run: mix deps.get
```

action run: 

https://github.com/thomas9911/bcrypt-rust/actions/runs/4707668411

Looked at the code and figured out it looks at this list:
https://repo.hex.pm/builds/otp/ubuntu-20.04/builds.txt

The version is in this list 🤔
