### ISSUE TITLE
Wrong OTP version installed

### ISSUE THREAD

**Issue by rlopzc** [erlef/setup-beam#215]
When using this:

```yaml
env:
  ImageOS: "ubuntu22"
  # Elixir and Erlang versions
  OTP_VERSION: "25.3.2.1"
  ELIXIR_VERSION: "1.14.5"
...
      - name: Setup Erlang, Elixir, etc
        uses: erlef/setup-beam@v1
        with:
          otp-version: ${{ env.OTP_VERSION }}
          elixir-version: ${{ env.ELIXIR_VERSION }}
```

The action outputs:
![image](https://github.com/erlef/setup-beam/assets/6199588/aea7d1de-3486-4361-93c8-257dd365cd1d)

![image](https://github.com/erlef/setup-beam/assets/6199588/b46d1c21-90e5-4dd6-90b7-6af5b145776f)

Not sure why the OTP version gets changed to `25.3.2.2` when it's `25.3.2.1`.
