### ISSUE TITLE
Support for mise (previously known as rtx)

### ISSUE THREAD

**Issue by mogest** [erlef/setup-beam#250]
Currently, setup-beam supports asdf's `.tool-versions` file.

A similar tool that is increasing in popularity is [mise](https://mise.jdx.dev/), previously known as rtx but recently renamed because of the naming conflict with NVIDIA's RTX graphics cards.

mise uses a `.mise.toml` file which fulfils a similar role to `.tool-versions`.  Here's an example of what one looks like:

```toml
[env]
_.file = '.env'
KERL_BUILD_DOCS="yes"

[tools]
elixir = "1.16.0-otp-26"
erlang = "26.2.1"
```

I'm happy to write a PR to support mise, but wanted to check in with the maintainers to see that it would be a valuable and accepted contribution first.
