### ISSUE TITLE
CI fails with "Could not install Erlang/OTP OTP-26.0.2 from any hex.pm mirror"

### ISSUE THREAD

**Issue by IwoHerka** [erlef/setup-beam#264]
#### The bug

```
| Installed Erlang/OTP version
| [command]/tmp/.setup-beam/otp/bin/erl -version
| qemu-x86_64: Could not open '/lib64/ld-linux-x86-64.so.2': No such file or directory
| /tmp/.setup-beam/otp/bin/erl: 57: exec: ./erts-14.0.2/bin/erlexec: not found
| Action install Erlang/OTP OTP-26.0.2 failed for mirror https://builds.hex.pm, with Error: The process '/tmp/.setup-beam/otp/bin/erl' failed with exit code 127
[Elixir CI/Build and test]   💬  ::debug::Stacktrace: Error: The process '/tmp/.setup-beam/otp/bin/erl' failed with exit code 127%0A    at ExecState._setResult (/run/act/actions/erlef-setup-beam@v1/dist/index.js:1702:25)%0A    at ExecState.CheckComplete (/run/act/actions/erlef-setup-beam@v1/dist/index.js:1685:18)%0A    at ChildProcess.<anonymous> (/run/act/actions/erlef-setup-beam@v1/dist/index.js:1579:27)%0A    at ChildProcess.emit (node:events:513:28)%0A    at maybeClose (node:internal/child_process:1100:16)%0A    at Socket.<anonymous> (node:internal/child_process:458:11)%0A    at Socket.emit (node:events:513:28)%0A    at Pipe.<anonymous> (node:net:301:12)
[Elixir CI/Build and test]   ❗  ::error::Could not install Erlang/OTP OTP-26.0.2 from any hex.pm mirror
[Elixir CI/Build and test]   ❌  Failure - Main Set up Elixir
[Elixir CI/Build and test]   ⚙  ::set-env:: INSTALL_DIR_FOR_OTP=/tmp/.setup-beam/otp
[Elixir CI/Build and test]   ⚙  ::add-path:: /tmp/.setup-beam/otp/bin
[Elixir CI/Build and test] exitcode '1': failure
[Elixir CI/Build and test]   🐳  docker exec cmd=[node /var/run/act/workflow/hashfiles/index.js] user= workdir=
[Elixir CI/Build and test]   🐳  docker exec cmd=[node /var/run/act/workflow/hashfiles/index.js] user= workdir=
[Elixir CI/Build and test] 🏁  Job failed
```

#### Software versions

A list of software versions where the bug is apparent, as detailed as possible:

```
    name: Build and test
    runs-on: ubuntu-22.04

    steps:
    - uses: actions/checkout@v3
    - name: Set up Elixir
      uses: erlef/setup-beam@v1
      with:
        elixir-version: '1.15.4-otp-26'
        otp-version: '26.0.2'
        fetch-depth: 0
 ```

#### How to replicate

An ordered list of steps to replicate the bug:

Run the task via `act -j build_and_test`.

#### Expected behaviour

CI should proceed to next step, having installed Erlang and Elixir.

#### Additional context

The CI worked previously, it seems that something happened in last few days.
