### ISSUE TITLE
Could not install Erlang/OTP master from any hex.pm mirror

### ISSUE THREAD

**Issue by pguyot** [erlef/setup-beam#296]
Starting today (?), master is no longer available. Restarting the run doesn't work.

See this run:
https://github.com/atomvm/AtomVM/actions/runs/9712387604/job/26807073004?pr=1220#step:3:18

```
Installing Erlang/OTP master - built on amd64/ubuntu-24.04
  aborted
  Waiting 16 seconds before trying again
  aborted
  Waiting 20 seconds before trying again
  Action install Erlang/OTP master failed for mirror https://builds.hex.pm,/ with Error: aborted
  Error: Could not install Erlang/OTP master from any hex.pm mirror
```

Action is invoked as follows:

```yaml
    - uses: erlef/setup-beam@v1
      with:
        otp-version: ${{ matrix.otp }}
        elixir-version: ${{ matrix.elixir_version }}
```

In this run, it fails with `matrix.otp` and `matrix.elixir_version` being equal to master with ubuntu-24.04.
```yaml
        # master version of OTP/Elixir
        - os: "ubuntu-24.04"
          cc: "cc"
          cxx: "c++"
          otp: "master"
          elixir_version: "master"
```
