### ISSUE TITLE
 Receiveing 404 when using "latest" - Installing Erlang/OTP 27.0 - built on amd64/ubuntu-22.04

### ISSUE THREAD

**Issue by Schultzer** [erlef/setup-beam#297]
#### The bug

Currently, we're receiving 404 from multiple mirrors when trying to install the latest OTP.

https://github.com/elixir-cldr/cldr/actions/runs/9829732424/job/27135101507
https://github.com/elixir-cldr/cldr/pull/230/files

```
Run erlef/setup-beam@v1
  with:
    otp-version: latest
    elixir-version: latest
    hexpm-mirrors: https://builds.hex.pm/
  https://cdn.jsdelivr.net/hex
  
    github-token: ***
    install-hex: true
    install-rebar: true
    version-type: loose
    disable_problem_matchers: false
  env:
    CLDR_PATH: /home/runner/work/cldr/cldr/integration-test-9829732424-69-1
```

```
Installing Erlang/OTP 27.0 - built on amd64/ubuntu-22.04
  Action install Erlang/OTP 27.0 failed for mirror https://builds.hex.pm,/ with Error: Unexpected HTTP response: 404
  Action install Erlang/OTP 27.0 failed for mirror https://cdn.jsdelivr.net/hex, with Error: Unexpected HTTP response: 404
```

#### Software versions

A list of software versions where the bug is apparent, as detailed as possible:

* `setup-beam`: 1.18

#### How to replicate

An ordered list of steps to replicate the bug: you could re-run the CLDR workflow our try to use latest.

#### Expected behaviour

Should install Erlang/OTP 27.0

#### Additional context

It would be helpful if the action produced better logs; I would love it if I could see the exact URL, headers, etc.
