### ISSUE TITLE
Frequent timeouts downloading builds from Hex

### ISSUE THREAD

**Issue by lpil** [erlef/setup-beam#300]
#### The bug

Builds are commonly failing due to timing out when reading builds from Hex

Here is one example: https://github.com/gleam-lang/gleam/actions/runs/10040640100/job/27747083505?pr=3419

#### Software versions
```yaml
Run erlef/setup-beam@v1
  with:
    otp-version: 26.1
    elixir-version: 1.16.1
    rebar3-version: 3
    github-token: ***
    install-hex: true
    install-rebar: true
    version-type: loose
    disable_problem_matchers: false
    hexpm-mirrors: https://builds.hex.pm/
```

#### How to replicate

An ordered list of steps to replicate the bug:
Run `setup-beam`

#### Expected behaviour

Erlang is installed.

#### Additional context

Thank you
