### ISSUE TITLE
Flaky Installer issues

### ISSUE THREAD

**Issue by isaacsanders** [erlef/setup-beam#306]
#### The bug

The tool cache install fails

#### Software versions

A list of software versions where the bug is apparent, as detailed as possible:

* `setup-beam`: 1.18.1
* `otp-version`: 25
* `elixir-version`: 1.16.3

#### How to replicate

An ordered list of steps to replicate the bug:

Invoke a workflow using the action similarly to the following:

```
      - name: Set up Elixir
        uses: erlef/setup-beam@b9c58b0450cd832ccdb3c17cc156a47065d2114f # v1.18.1
        with:
          otp-version: "25"
          elixir-version: "1.16.3"
```

This won't always fail, but it fails often enough to raise concerns.

#### Expected behaviour

The versions should be installed and interact with the GHA cache normally.

#### Additional context

GHES 3.10

This is the error I'm seeing:

```
Action install Erlang/OTP OTP-25.3.2.13 failed for mirror https://builds.hex.pm/, with Error: File was unable to be removed Error: ENOTEMPTY: directory not empty, rmdir '/opt/hostedtoolcache/otp/ubuntu-22.04/OTP-25.3.2.13/x64/lib'
```
