### ISSUE TITLE
Support for installing 32-bit Elixir on Windows

### ISSUE THREAD

**Issue by gilbertbw** [erlef/setup-beam#315]
#### Is your feature request related to a problem?

I need to build a 32-bit Windows `mix release` of my project, but this Action only installs the 64bit version of Erlang/OTP and Elixir.

#### Describe the feature you'd like

I would like the ability to specify which processor architecture of OTP/Erlang to install, when running on windows.

I am picturing something like:
```yaml
  blah:
    name: Create release
    runs-on: windows-2022
    steps:
    - name: Set up Elixir
      uses: erlef/setup-beam@v1
      with:
        version-type: strict
        otp-version: "27.2"
        elixir-version: "1.18.1-otp-27"
        architecture: "win32"
```

#### Describe alternatives you've considered

N/A

#### Additional context
I think this would require updating `install` for win32 opt:
https://github.com/erlef/setup-beam/blob/e5b66193a0ae8fd3e4c0296f0c7a1c7d36241444/src/setup-beam.js#L801-L802
to optionally use the `win32` version. I see that elixir releases appear to be platform agnostic, so no change is required there?

I see that for Linux bob builds of OTP are used, and bob only builds 64bit releases. So I don't think it's possible to easily support this option for Linux environments.
