### ISSUE TITLE
ubuntu-latest change does not include libssl1.1

### ISSUE THREAD

**Issue by djbberko** [erlef/setup-beam#318]
#### The bug

Github runners updated `ubuntu-latest` to use 24.04, which does not include libssl1.1. See here: https://github.com/actions/runner-images/issues/10636
This breaks the action with the following error: 
```Running mix local.rebar,--force
  /home/runner/work/_temp/.setup-beam/elixir/bin/mix local.rebar --force
  
  Error: 22:13:59.705 [error] Unable to load crypto library. Failed with error:
  ":load_failed, Failed to load NIF library /home/runner/work/_temp/.setup-beam/otp/lib/crypto-5.1.2/priv/lib/crypto: 'libcrypto.so.1.1: cannot open shared object file: No such file or directory'"
  OpenSSL might not be installed on this system.
  
  ** (Mix) httpc request failed with: {:failed_connect, [{:to_address, {'builds.hex.pm', 443}}, {:inet, [:inet], {:eoptions, {:undef, [{:crypto, :supports, [], []}, {:tls_record, :sufficient_support, 1, [file: 'tls_record.erl', line: 772]}, {:tls_record, :supported_protocol_versions, 1, [file: 'tls_record.erl', line: 392]}, {:tls_record, :supported_protocol_versions, 0, [file: 'tls_record.erl', line: 380]}, {:ssl, :handle_option, 4, [file: 'ssl.erl', line: 1906]}, {:ssl, :process_options, 3, [file: 'ssl.erl', line: 1585]}, {:ssl, :handle_options, 5, [file: 'ssl.erl', line: 1537]}, {:ssl, :connect, 4, [file: 'ssl.erl', line: 618]}]}}}]}
  
  Could not install Rebar because Mix could not download metadata at https://builds.hex.pm/installs/rebar3-1.x.csv.
  
  Action mix rebar failed for mirror https://builds.hex.pm,/ with Error: The process '/home/runner/work/_temp/.setup-beam/elixir/bin/mix' failed with exit code 1
  Error: Could not mix rebar from any hex.pm mirror
```

#### How to replicate

An ordered list of steps to replicate the bug:

1. run  an action on `ubuntu-latest`

#### Expected behaviour

Install BEAM succesfully.

#### Additional context

Any other context about the bug.

**Comment by starbelly** [comment]
Do you have a way to reproduce this? I'm not having issues, and have tested across a few projects, so a few more details would help. Specifically, versions of erlang, elixir, etc. Even better would be a failed run or workflow file.

**Comment by djbberko** [comment]
> Do you have a way to reproduce this? I'm not having issues, and have tested across a few projects, so a few more details would help. Specifically, versions of erlang, elixir, etc. Even better would be a failed run or workflow file.

I have seen this issue in both OTP 24 and 25. I unfortunately cannot share the workflow itself since it is in a private repository. Maybe the full error output will help?

```Run erlef/setup-beam@v1
Installing Erlang/OTP OTP-25.1.2.1 - built on amd64/ubuntu-20.04
  /usr/bin/tar zx --strip-components=1 --warning=no-unknown-keyword --overwrite -C /home/runner/work/_temp/3ffdfa85-e042-4309-9500-c1ff77a0d36a -f /home/runner/work/_temp/7b55474a-6772-4505-a7c7-748ef3f3daad
  /home/runner/work/_temp/.setup-beam/otp/Install -minimal /home/runner/work/_temp/.setup-beam/otp
  Installed Erlang/OTP version
  /home/runner/work/_temp/.setup-beam/otp/bin/erl -version
  Erlang (SMP,ASYNC_THREADS) (BEAM) emulator version 13.1.2.1
Using Elixir 1.14.2 (built for Erlang/OTP 25)
Installing Elixir v1.14.2-otp-25
  /usr/bin/unzip -o -q /home/runner/work/_temp/984ab6ab-b323-4929-9205-cedea2e7e549
  Installed Elixir version
  /home/runner/work/_temp/.setup-beam/elixir/bin/elixir -v
  Erlang/OTP 25 [erts-13.1.2.1] [source] [64-bit] [smp:2:2] [ds:2:2:10] [async-threads:1] [jit:ns]
  
  Elixir 1.14.2 (compiled with Erlang/OTP 25)
Running mix local.rebar,--force
  /home/runner/work/_temp/.setup-beam/elixir/bin/mix local.rebar --force
  
  Error: 22:13:59.705 [error] Unable to load crypto library. Failed with error:
  ":load_failed, Failed to load NIF library /home/runner/work/_temp/.setup-beam/otp/lib/crypto-5.1.2/priv/lib/crypto: 'libcrypto.so.1.1: cannot open shared object file: No such file or directory'"
  OpenSSL might not be installed on this system.
  
  ** (Mix) httpc request failed with: {:failed_connect, [{:to_address, {'builds.hex.pm', 443}}, {:inet, [:inet], {:eoptions, {:undef, [{:crypto, :supports, [], []}, {:tls_record, :sufficient_support, 1, [file: 'tls_record.erl', line: 772]}, {:tls_record, :supported_protocol_versions, 1, [file: 'tls_record.erl', line: 392]}, {:tls_record, :supported_protocol_versions, 0, [file: 'tls_record.erl', line: 380]}, {:ssl, :handle_option, 4, [file: 'ssl.erl', line: 1906]}, {:ssl, :process_options, 3, [file: 'ssl.erl', line: [15](https://github.com/adRise/apollo/actions/runs/12918024493/job/36025728265#step:4:16)85]}, {:ssl, :handle_options, 5, [file: 'ssl.erl', line: 1537]}, {:ssl, :connect, 4, [file: 'ssl.erl', line: 618]}]}}}]}
  
  Could not install Rebar because Mix could not download metadata at https://builds.hex.pm/installs/rebar3-1.x.csv.
  
  Action mix rebar failed for mirror https://builds.hex.pm, with Error: The process '/home/runner/work/_temp/.setup-beam/elixir/bin/mix' failed with exit code 1
  Error: Could not mix rebar from any hex.pm mirror
```

**Comment by starbelly** [comment]
> > Do you have a way to reproduce this? I'm not having issues, and have tested across a few projects, so a few more details would help. Specifically, versions of erlang, elixir, etc. Even better would be a failed run or workflow file.
> 
> I have seen this issue in both OTP 24 and 25. I unfortunately cannot share the workflow itself since it is in a private repository. Maybe the full error output will help?
> 
> ```
> Installing Erlang/OTP OTP-25.1.2.1 - built on amd64/ubuntu-20.04
>   /usr/bin/tar zx --strip-components=1 --warning=no-unknown-keyword --overwrite -C /home/runner/work/_temp/3ffdfa85-\


Shot in the dark here, but I ran into a similar issue the other day, it turned out I had `ImageOS` set in the env, which overrode what setup-beam attempted to detect. This was left over from temporarily moving to self-hosted runners for a bit, then back to github runners, but wasn't a problem until the recent update. 

If this turns out to be the issue, what should be done perhaps is to insert a `determined via ...` in setup-beam, this might be helpful.

**Comment by starbelly** [comment]
Hi @djbberko did you see if what I stated as a hypothesis could be disproved?

**Comment by serpent213** [comment]
Hi folks,

setting up a Gitea Actions Runner for a Phoenix project, I stumbled upon this issue.

Workflow file is based on the template, added MinIO:

<details>
<summary><code>workflow.yaml</code></summary>

```yaml
name: Heimdall Mix Tests

# Define workflow that runs when changes are pushed to the
# `main` branch or pushed to a PR branch that targets the `main`
# branch. Change the branch name if your project uses a
# different name for the main branch like "master" or "production".
on: [push, pull_request]

# Sets the ENV `MIX_ENV` to `test` for running tests
env:
  MIX_ENV: test
  MINIO_ROOT_USER: minio
  MINIO_ROOT_PASSWORD: miniosecret

permissions:
  contents: read

jobs:
  test:
    # Set up a Postgres DB service. By default, Phoenix applications
    # use Postgres. This creates a database for running tests.
    # Additional services can be defined here if required.
    services:
      pgsql:
        image: postgres:latest
        ports: ['5432:5432']
        env:
          POSTGRES_USER: dev
          POSTGRES_PASSWORD: dev
        options: >-
          --health-cmd pg_isready
          --health-interval 10s
          --health-timeout 5s
          --health-retries 5

      minio:
        image: bitnami/minio:latest
        ports: ['9000:9000']
        # env:
        #   MINIO_ROOT_USER: minio
        #   MINIO_ROOT_PASSWORD: minio
        options: >-
          --health-cmd "curl -I http://localhost:9000/minio/health/live"
          --health-interval 10s
          --health-timeout 5s
          --health-retries 6
          --health-start-period 30s

    runs-on: ubuntu-latest
    name: Heimdall Mix Tests
    # name: Test on OTP ${{matrix.otp}} / Elixir ${{matrix.elixir}}
    strategy:
      # Specify the OTP and Elixir versions to use when building
      # and running the workflow steps.
      matrix:
        otp: ['25.3.2']       # Define the OTP version [required]
        elixir: ['1.17.3']    # Define the elixir version [required]
    steps:
    # Step: Setup Elixir + Erlang image as the base.
    - name: Set up Elixir
      uses: erlef/setup-beam@v1
      with:
        otp-version: ${{matrix.otp}}
        elixir-version: ${{matrix.elixir}}

    # Step: Check out the code.
    - name: Checkout code
      uses: actions/checkout@v4

    # Step: Define how to cache deps. Restores existing cache if present.
    - name: Cache deps
      id: cache-deps
      uses: actions/cache@v3
      env:
        cache-name: cache-elixir-deps
      with:
        path: deps
        key: ${{ runner.os }}-mix-${{ env.cache-name }}-${{ hashFiles('**/mix.lock') }}
        restore-keys: |
          ${{ runner.os }}-mix-${{ env.cache-name }}-

    # Step: Define how to cache the `_build` directory. After the first run,
    # this speeds up tests runs a lot. This includes not re-compiling our
    # project's downloaded deps every run.
    - name: Cache compiled build
      id: cache-build
      uses: actions/cache@v3
      env:
        cache-name: cache-compiled-build
      with:
        path: _build
        key: ${{ runner.os }}-mix-${{ env.cache-name }}-${{ hashFiles('**/mix.lock') }}
        restore-keys: |
          ${{ runner.os }}-mix-${{ env.cache-name }}-
          ${{ runner.os }}-mix-

    # Step: Download project dependencies. If unchanged, uses
    # the cached version.
    - name: Install dependencies
      run: mix deps.get

    # Step: Compile the project treating any warnings as errors.
    # Customize this step if a different behavior is desired.
    - name: Compiles without warnings
      run: mix compile
      # run: mix compile --warnings-as-errors

    # Step: Check that the checked in code has already been formatted.
    # This step fails if something was found unformatted.
    # Customize this step as desired.
    - name: Check Formatting
      run: mix format --check-formatted

    # Step: Execute the tests.
    - name: Setup DB and Assets
      run: mix setup

    # Step: Execute the tests.
    - name: Run tests
      run: |
        mix test || true
        sleep 3600
```

</details>

<details>
<summary>Set up Elixir step logs</summary>

```
::group::Installing Erlang/OTP OTP-25.3.2.16 - built on amd64/ubuntu-20.04
[2](https://git.example/XPL/heimdall/actions/runs/25#jobstep-1-2)
[command]/usr/bin/tar zx --strip-components=1 --warning=no-unknown-keyword --overwrite -C /tmp/76a1696c-9fb9-406e-9d91-1d1f7ad37436 -f /tmp/c833402a-517b-4c75-9795-4298697335cb
[3](https://git.example/XPL/heimdall/actions/runs/25#jobstep-1-3)
[command]/tmp/.setup-beam/otp/Install -minimal /tmp/.setup-beam/otp
[4](https://git.example/XPL/heimdall/actions/runs/25#jobstep-1-4)
Installed Erlang/OTP version
[5](https://git.example/XPL/heimdall/actions/runs/25#jobstep-1-5)
[command]/tmp/.setup-beam/otp/bin/erl -version
[6](https://git.example/XPL/heimdall/actions/runs/25#jobstep-1-6)
Erlang (SMP,ASYNC_THREADS) (BEAM) emulator version 13.2.2.12
[7](https://git.example/XPL/heimdall/actions/runs/25#jobstep-1-7)
::endgroup::
[8](https://git.example/XPL/heimdall/actions/runs/25#jobstep-1-8)
Using Elixir 1.17.3 (built for Erlang/OTP 25)
[9](https://git.example/XPL/heimdall/actions/runs/25#jobstep-1-9)
::group::Installing Elixir v1.17.3-otp-25
[10](https://git.example/XPL/heimdall/actions/runs/25#jobstep-1-10)
Installed Elixir version
[11](https://git.example/XPL/heimdall/actions/runs/25#jobstep-1-11)
[command]/tmp/.setup-beam/elixir/bin/elixir -v
[12](https://git.example/XPL/heimdall/actions/runs/25#jobstep-1-12)
Erlang/OTP 25 [erts-13.2.2.12] [source] [64-bit] [smp:32:6] [ds:32:6:10] [async-threads:1] [jit:ns]
[13](https://git.example/XPL/heimdall/actions/runs/25#jobstep-1-13)
[14](https://git.example/XPL/heimdall/actions/runs/25#jobstep-1-14)
Elixir 1.17.3 (compiled with Erlang/OTP 25)
[15](https://git.example/XPL/heimdall/actions/runs/25#jobstep-1-15)
##[add-matcher]/run/act/actions/7c0d8ed7f53b94922866a2ffb6fde3823398b21f2476f74350a77adac5a7c7fe/dist/elixir-matchers.json
[16](https://git.example/XPL/heimdall/actions/runs/25#jobstep-1-16)
::endgroup::
[17](https://git.example/XPL/heimdall/actions/runs/25#jobstep-1-17)
::group::Running mix local.rebar,--force
[18](https://git.example/XPL/heimdall/actions/runs/25#jobstep-1-18)
[command]/tmp/.setup-beam/elixir/bin/mix local.rebar --force
[19](https://git.example/XPL/heimdall/actions/runs/25#jobstep-1-19)
[20](https://git.example/XPL/heimdall/actions/runs/25#jobstep-1-20)
10:06:30.426 [error] Unable to load crypto library. Failed with error:
[21](https://git.example/XPL/heimdall/actions/runs/25#jobstep-1-21)
":load_failed, Failed to load NIF library /tmp/.setup-beam/otp/lib/crypto-5.1.4.3/priv/lib/crypto: 'libcrypto.so.1.1: cannot open shared object file: No such file or directory'"
[22](https://git.example/XPL/heimdall/actions/runs/25#jobstep-1-22)
OpenSSL might not be installed on this system.
[23](https://git.example/XPL/heimdall/actions/runs/25#jobstep-1-23)
[24](https://git.example/XPL/heimdall/actions/runs/25#jobstep-1-24)
** (Mix) httpc request failed with: {:failed_connect, [{:to_address, {~c"builds.hex.pm", 443}}, {:inet, [:inet], {:eoptions, {:undef, [{:crypto, :supports, [], []}, {:tls_record, :sufficient_support, 1, [file: ~c"tls_record.erl", line: 772]}, {:tls_record, :supported_protocol_versions, 1, [file: ~c"tls_record.erl", line: 392]}, {:tls_record, :supported_protocol_versions, 0, [file: ~c"tls_record.erl", line: 380]}, {:ssl, :handle_option, 4, [file: ~c"ssl.erl", line: 1910]}, {:ssl, :process_options, 3, [file: ~c"ssl.erl", line: 1582]}, {:ssl, :handle_options, 5, [file: ~c"ssl.erl", line: 1534]}, {:ssl, :connect, 4, [file: ~c"ssl.erl", line: 624]}]}}}]}
[25](https://git.example/XPL/heimdall/actions/runs/25#jobstep-1-25)
[26](https://git.example/XPL/heimdall/actions/runs/25#jobstep-1-26)
Could not install Rebar because Mix could not download metadata at https://builds.hex.pm/installs/rebar3-1.x.csv.
[27](https://git.example/XPL/heimdall/actions/runs/25#jobstep-1-27)
[28](https://git.example/XPL/heimdall/actions/runs/25#jobstep-1-28)
Action mix rebar failed for mirror https://builds.hex.pm, with Error: The process '/tmp/.setup-beam/elixir/bin/mix' failed with exit code 1
[29](https://git.example/XPL/heimdall/actions/runs/25#jobstep-1-29)
::error::Could not mix rebar from any hex.pm mirror
```

</details>

Runner config:

```nix
    labels = [
      # NixOS example config
      # fake the ubuntu name, because node provides no ubuntu builds
      # "ubuntu-latest:docker://node:20-bookworm"
      # "ubuntu-22:docker://node:20-bookworm"
      # "ubuntu-20:docker://node:20-bullseye"
      # Gitea example config
      "ubuntu-latest:docker://gitea/runner-images:ubuntu-latest"
      "ubuntu-22.04:docker://gitea/runner-images:ubuntu-22.04"
      "ubuntu-20.04:docker://gitea/runner-images:ubuntu-20.04"
    ];
```
I'm new to Action Runner and not a Docker expert, still trying to make sense of these labels thing (and mapping Ubuntu to Debian...?). Anyway, the above log is from running with `docker://gitea/runner-images:ubuntu-latest`, also `docker://node:20-bookworm` results in the same libcrypto error.

Got it to work with `docker://node:20-bullseye`, but that opens other gates to dependency hell in my setup.
