### ISSUE TITLE
Incompatible ImageOS on ubuntu 24 runner (large runner)

### ISSUE THREAD

**Issue by iStefo** [erlef/setup-beam#325]
#### The bug

A few days ago, our GH actions builds using this action broke. I can't pinpoint the exact date, last known good run was on April 9.

The action fails with this error message:

> Tried to map a target OS from env. variable 'ImageOS' (got Linux), but failed. If you're using a self-hosted runner, you should set 'env': 'ImageOS': ... to one of the following: ['ubuntu18', 'ubuntu20', 'ubuntu22', 'ubuntu24', 'win19', 'win22']

#### Software versions

* `setup-beam`: v1, SHA:5304e04ea2b355f03681464e683d92e3b2f18451
* VM Image
  - OS: Linux (arm64)
  - Source: Partner
  - Name: Ubuntu 24.04 by Arm Limited
  - Version: 20250408.15.1

`ImageOS` when printed via `env`: `Linux`

A month ago, it worked with this VM image:

```
VM Image
  OS: Linux (arm64)
  Source: Marketplace
  Publisher: arm
  Offer: github_arm_linux_runner_2404
  Plan: github_arm_linux_runner_plan_2404
  Version: 1.0.11
```

Unfortunately, I can't provide the exact value of `ImageOS` in env for that older version because it was not logged.

#### How to replicate

1. Create a large (ARM) runner using Ubuntu 24.04
2. Run a workflow using the `erlef/setup-beam@v1` action

#### Expected behaviour

The action determines the relevant info on its own/does not fail on a standard ubuntu image provided by GitHub.

#### Additional context

We worked around the issue by setting ImageOS for the erlef/setup-beam action like this:

```yml
      - name: Set ImageOS Env (fix for erlef/setup-beam)
        id: erlef-fix
        run: |
          VSN=$(cat /etc/os-release | grep VERSION_ID | awk -F '"' '{ print $2 }' | awk -F "." '{ print $1 }')
          echo "ImageOS=ubuntu${VSN}" >> $GITHUB_OUTPUT

      - name: Set up Elixir
        uses: erlef/setup-beam@v1
        with:
          version-file: .tool-versions
          version-type: strict
        env:
          ImageOS: ${{ steps.erlef-fix.outputs.ImageOS }}
```
