### ISSUE TITLE
Cannot use Elixir 1.18-otp-27 with OTP 28

### ISSUE THREAD

**Issue by kevinschweikert** [erlef/setup-beam#329]
#### The bug

Cannot use Elixir 1.18-otp-27 with OTP 28 as a combination

#### Software versions

A list of software versions where the bug is apparent, as detailed as possible:

* `setup-beam`: v1

#### How to replicate

An ordered list of steps to replicate the bug:

```yaml
      matrix:
        include:
          - elixir: '1.18.4-otp-27'
            otp: '28.0'

...

      uses: erlef/setup-beam@v1
      with:
        elixir-version: ${{ matrix.elixir }}
        otp-version: ${{ matrix.otp }}

```

```
Error: Requested Elixir / Erlang/OTP version (1.18.4-otp-27 / 28.0) not found in version list (did you check Compatibility between Elixir and Erlang/OTP?).Elixir and Erlang/OTP compatibility can be found at: https://hexdocs.pm/elixir/compatibility-and-deprecations.html
```

#### Expected behaviour

From https://hexdocs.pm/elixir/compatibility-and-deprecations.html

| Elixir version	| Supported Erlang/OTP versions |
| --- | ---|
| 1.18	| 25 - 27 (and Erlang/OTP 28 from v1.18.4)|

#### Additional context

- https://github.com/wemake-services/recase/pull/217
