### ISSUE TITLE
Cannot run ubuntu-24.04 / Elixir 1.18.4 / OTP 28

### ISSUE THREAD

**Issue by lud** [erlef/setup-beam#344]
#### The bug

The README.md file tells that Ubuntu 24.04 supports OTP 28 and the compatibility page tells that Elixir 1.18.4 supports OTP 28.

#### Software versions

```yaml
runs-on: ubuntu-24.04

strategy:
  matrix:
    elixir: ["1.18.4"]
    otp: ["28"]

name: "Test ${{matrix.elixir}}-otp-${{matrix.otp}}"

steps:
  - uses: actions/checkout@v4

  - uses: erlef/setup-beam@v1
    with:
      otp-version: ${{matrix.otp}}
      elixir-version: ${{matrix.elixir}}
```

#### How to replicate

Example error here: https://github.com/lud/jsv/actions/runs/15522835608/job/43698351211
CI config here: https://github.com/lud/jsv/blob/another-ci-try/.github/workflows/elixir.yaml

#### Additional context

I am not sure to know what I am missing here. My basic setup used to work well for previous versions, there is nothing special about it.

Thank you.
