### ISSUE TITLE
Action crashing on Github

### ISSUE THREAD

**Issue by Gustavo-Ziaugra-Arvo** [erlef/setup-beam#350]
#### The bug

Hi, 
We just started to see this error this morning using the setup-beam step.

<img width="661" alt="Image" src="https://github.com/user-attachments/assets/0ea03e5f-35b0-4609-9d88-9fd7b7b7beda" />

Do someone knows what may be going on?
Thanks in advance for this amazing action.
Zig

#### Software versions

```yml
 steps:
      - uses: actions/checkout@v4
      - uses: erlef/setup-beam@v1
        with:
          elixir-version: ${{needs.versions.outputs.elixir}}
          otp-version: ${{needs.versions.outputs.otp}}
```

**Comment by paulo-ferraz-oliveira** [comment]
Doesn't break for me: https://github.com/paulo-ferraz-oliveira/setup-beam-example/actions/runs/15883789625/job/44790626318#step:3:2

So I'll need further information... Unfortunately I don't have self-hosted runners available so debugging is much harder. Can you create a minimal repo. where you try to isolate the issue?

**Comment by Gustavo-Ziaugra-Arvo** [comment]
@paulo-ferraz-oliveira  Hi Paulo, we are not using a self-hosted runner, it just started randomly. I will try to get a repo and return to you here with more infos

**Comment by Gustavo-Ziaugra-Arvo** [comment]
@paulo-ferraz-oliveira Here's a PR: https://github.com/Gustavo-Ziaugra-Arvo/setup-beam-bug-350/actions/runs/15884596302/job/44793311206

**Comment by sufyanadam** [comment]
@Gustavo-Ziaugra-Arvo confirmed reverting to v1.19.0 works

**Comment by paulo-ferraz-oliveira** [comment]
I'll test (in the above repo) with your workflow file verbatim.

**Comment by paulo-ferraz-oliveira** [comment]
My latest test, where I have 

```yml
        uses: erlef/setup-beam@v1
        with:
          # using a mix of single, quote and no-quote
          elixir-version: '1.18.4'
          otp-version: "27.3"
          rebar3-version: 3.25
```

passes, so this is some GitHub Actions -specific stuff when passing a value through the environment. I'm not sure we should support a hack for this, but I'll give it a thought regarding our tests...

**Comment by paulo-ferraz-oliveira** [comment]
The GitHub UI is also misleading, since you see `'1.18.4'` as per the examples, but that's not what you're sending to the action.

**Comment by paulo-ferraz-oliveira** [comment]
But wait... what's also strange is that it apparently installed Erlang/OTP and then crashes on reporting the installed version 😕

**Comment by paulo-ferraz-oliveira** [comment]
@Gustavo-Ziaugra-Arvo, @sufyanadam, is this the same case, that you're passing in versions that have `'`? Because if that's so, I'm not sure we should be messing with the consumer's input in trying to coerce versions to what they're not.

You're passing a string that is a single-quote -wrapped term, not a string.

**Comment by sufyanadam** [comment]
> [@Gustavo-Ziaugra-Arvo](https://github.com/Gustavo-Ziaugra-Arvo), [@sufyanadam](https://github.com/sufyanadam), is this the same case, that you're passing in versions that have `'`? Because if that's so, I'm not sure we should be messing with the consumer's input in trying to coerce versions to what they're not.
> 
> You're passing a string that is a single-quote -wrapped term, not a string.

In our pipeline we're not passing any quotes. This was working before v1.21.0 . We have reverted and locked down to v1.19.0 to unblock our CI pipelines and avoid issues in the future. My recommendation would be to analyze the diff between the changes and revert to what was working before, as I'm sure many more folks are running into the same issue if they're referencing `v1` which will essentially pull `v1.21.0`, which is the problematic version.

<img width="1309" alt="Image" src="https://github.com/user-attachments/assets/9fdcfbb0-f858-40cf-a925-4a94120968c6" />

This had been working up until this morning (Pacific Daylight Time)

<img width="427" alt="Image" src="https://github.com/user-attachments/assets/e212f7d5-18ef-4759-8b33-41f31d9b24e5" />

**Comment by paulo-ferraz-oliveira** [comment]
Can you post an example repo where we can see this happen?

In your case, I'd start by removing `ref:`, also, since it's mentioned nowhere in the `README.md` that it's supported.

But I'd like to verify where the issue's coming from.

**Comment by paulo-ferraz-oliveira** [comment]
@Gustavo-Ziaugra-Arvo, where you passing a `'` and were able to fix it by removing it?

**Comment by paulo-ferraz-oliveira** [comment]
I tried to implement some validation on input, but I got to a point where it became more complex than it's worth.

Input types are:

- bool (but not really something we need to validate due to JavaScript's truthy-comparison nature)
  - inputs: `install-rebar`, `install-hex`, `disable_problem_matchers` 
- list
  - inputs: `otp-architecture` (already validated), `version-type` (not validated)
- regex
  - inputs: `otp-version`, `elixir-version`, `gleam-version`, `rebar3-version`

The complicated stuff is in the regex, as expected.

While we typically suggest deterministic versions (we even do so for the action itself [in the README](https://github.com/erlef/setup-beam?tab=readme-ov-file#versioning)), consumers are free to use versions like `1.4`, for which we'll try to find the best result as `>1.4` or similar (not all semver ranges and expressions are tested).

For OTP, given its complex versioning scheme we even [recommend specifying exact versions](https://github.com/erlef/setup-beam?tab=readme-ov-file#strict-versions).

Also:

- in OTP, you can use `OTP-` or do without it
- in Elixir, you can use `-otp-` or do without it

There's also the `-rc` which recently even sparked discussion around the documentation, that ended up being tweaked for clarity.

From the top of my head:

- `main`
- `master`
- `master-otp-_`
- `maint-_`
- `main-otp-_`
- `OTP-_`
- `x`
- `x.y`
- `x.y.z`
- `x.y.z-otp-.`
- `nightly`
- `latest`
- `_-rc_`
- with `v` and without `v`

So, supporting removing `'`, and/or `ref:` when this is not mentioned in the doc. or tests will eventually be a burden the maintainers won't want.

Fwiw, finally, the README mentions:

- `>x`
- `OTP-x.y`
- `vx.y-otp-.`
- `vx.y.z`
- `vx.y.z-rc.0`
- `x`
- `x.y`
- `x.y.z`

which is pretty standard stuff we support.

**Comment by Gustavo-Ziaugra-Arvo** [comment]
@paulo-ferraz-oliveira  Removing the internal '' from the version solved the problem for us. we were able to go back to the latest version of this repo after this change. 

```yml
jobs:
  versions:
    name: Export Versions
    outputs:
      elixir: ${{steps.elixir.outputs.value }}
      otp: ${{ steps.otp.outputs.value }}
      node: ${{ steps.node.outputs.node.value }}
    steps:
      - id: elixir
        run: echo "value=1.18.4" >> $GITHUB_OUTPUT
      - id: otp
        run: echo "value=27.3" >> $GITHUB_OUTPUT
      - id: node
        run: echo "value=20.0.0" >> $GITHUB_OUTPUT

  pre_build:
    name: Pre Build
    needs: [versions]
    runs-on: clarus-linux-16cores
    steps:
      - name: Checkout Github repo
        uses: actions/checkout@v4

      - name: Sets up an Erlang/OTP environment
        uses: erlef/setup-beam@v1
        with:
          elixir-version: ${{needs.versions.outputs.elixir}}
          otp-version: ${{needs.versions.outputs.otp}}


```
