### ISSUE TITLE
Add action for macOS

### ISSUE THREAD

**Issue by paulo-ferraz-oliveira** [erlef/setup-beam#54]

**Comment by wojtekmach** [comment]
This is tricky because while we have OTP images for Linux and Windows, we don't have such for macOS.

We hope to address it in https://github.com/erlang/otp/issues/4487.

In the meantime, I think we could wrap Homebrew. This workflow:

```yaml
runs-on: macos-10.5
steps:
  - uses: erlef/setup-beam@v1
    with:
      otp-version: 23
```

would under the hood call:

```
$ brew install erlang@23
```

At this moment we can run:

- `$ brew install erlang` (OTP 24)
- `$ brew install erlang@23`
- `$ brew install erlang@22`
- `$ brew install erlang@21`

See: https://formulae.brew.sh/formula/erlang

We can't install particular versions, e.g. 23.3.0, and these versions are moving targets, but I think that's OK.

If we're to move forward with this homebrew based solution, it begs the question why not let the users do it themselves. I think having this in the action would allow nice things like:

```yaml
strategy:
  fail-fast: false
  matrix:
    os: [ubuntu-latest, macos-latest, windows-latest]
    otp: [24]
    include:
      - os: ubuntu-latest
        otp-version: 23
runs-on: ${{matrix.os}}
steps:
  - uses: erlef/setup-beam@v1
    with:
      otp-version: ${{matrix.otp}}
```

Furthermore, the action could cache homebrew stuff which would be a nice win for users too.

WDYT?
