### ISSUE TITLE
Error: Requested Erlang/OTP version (from spec 19.x) not found in build listing

### ISSUE THREAD

**Issue by kianmeng** [erlef/setup-beam#55]
I've switched to `elfef/setup-elixir` and noticed the CI cannot find Erlang/OTP `19.x`.

The config as follows:
```yaml
jobs:
  build:
    name: mix test (Elixir ${{matrix.elixir}} | Erlang/OTP ${{matrix.otp}})
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        include:
          - elixir: '1.7.x'
            otp: '19.x'
          - elixir: '1.11.x'
            otp: '23.x'
            check_formatted: true
...
```
It used to work last time as well as for `Elixir 1.11.x` and `Erlang/OTP 23.x`. 
It's a bug or I miss out something in my config?
