### ISSUE TITLE
OTP version undefined

### ISSUE THREAD

**Issue by jordanbcooper** [erlef/setup-beam#56]
Unsure if this is from today's changes, but we suddenly get:

`Installing Erlang/OTP undefined - built on ubuntu-20.04
  /home/runner/work/_actions/erlef/setup-elixir/v1/dist/install-otp.sh ubuntu-20.04 undefined
  Error: The process '/home/runner/work/_actions/erlef/setup-elixir/v1/dist/install-otp.sh' failed with exit code 8`

We're not having this issue with OTP 24.0.3, but it seems to be a sudden issue with otp-version: 22.3.4.2 ?

**Comment by jordanbcooper** [comment]
@paulo-ferraz-oliveira  Would this have anything to do with your recent merge?

**Comment by paulo-ferraz-oliveira** [comment]
> @paulo-ferraz-oliveira Would this have anything to do with your recent merge?

I'm not sure. Could you point me to a `.yml` so I can examine it better?

Are you actually using `22.3.4.2` as the input?

**Comment by jordanbcooper** [comment]
Yes, we are actually using that as the input:

`      - name: Setup elixir
        uses: erlef/setup-elixir@v1
        with:
          elixir-version: '1.11.0'
          otp-version: '22.3.4.2'`

**Comment by jordanbcooper** [comment]
We JUST tried that one too, 
![image](https://user-images.githubusercontent.com/13210689/124962451-a34de880-dfec-11eb-88ac-45ad4289f2b6.png)


Output:

`Installing Erlang/OTP OTP-22.3.4.2 - built on ubuntu-20.04
  /home/runner/work/_actions/erlef/setup-elixir/v1/dist/install-otp.sh ubuntu-20.04 OTP-22.3.4.2
  
  Installed Erlang/OTP version follows
  Erlang (SMP,ASYNC_THREADS,HIPE) (BEAM) emulator version 10.7.2.1
Error: Requested Elixir / Erlang/OTP version (v1.11.0-otp-22 / OTP-22.3.4.2) should not contain '-otp-...'`

**Comment by paulo-ferraz-oliveira** [comment]
Did you try without '-otp-...'? Because that should be inferred from the Erlang version.

**Comment by paulo-ferraz-oliveira** [comment]
The action is semver based, as much as possible, but some versions (like OTP's) are not, which makes us have to choose between offering a "range" -like function or be strict in versions (which is why the option I just mentioned was introduced).

As an example, take '22.3'. Some might want '22.3' exactly, some might want '22.3.1' and some '22.3.1'. We chose "ranges" by default, but it might not suit everyone: we hope it suits the majority, since this was the default behaviour.

**Comment by jordanbcooper** [comment]
I see. Without OTP, going back to 1.11.0 and using strict we get this:

![image](https://user-images.githubusercontent.com/13210689/124963317-a695a400-dfed-11eb-8691-daee8890ffe0.png)

**Comment by paulo-ferraz-oliveira** [comment]
Did you remove the `v` from the Elixir version?

I'm drafting #57, as a means to potentially solve your issue. This was a hidden bug, as previous behaviour was supposed to be semver -based, but apparently was not (fixing that surfaced your issue).

**Comment by vanvoljg** [comment]
I have a similar error that started happening this morning. It's slightly different, but feels like it may be related.

Actions output:

![Screenshot_20210708_100225](https://user-images.githubusercontent.com/42327429/124964312-bbfed400-dfd5-11eb-9711-f25867091861.png)

Config:

```yml
env:
  MIX_ENV: test
  OTP_VERSION_SPEC: "24.0.2"
  ELIXIR_VERSION_SPEC: "1.12.1"

jobs:
  compile:
    name: Compile
    steps:
      - uses: erlef/setup-beam@v1
        id: setup
        with:
          otp-version: ${{ env.OTP_VERSION_SPEC }}
          elixir-version: ${{ env.ELIXIR_VERSION_SPEC }}
          version-type: "strict"
```

**Comment by jordanbcooper** [comment]
Adding the v back to the elixir version fixed this for us @paulo-ferraz-oliveira , thank you

**Comment by paulo-ferraz-oliveira** [comment]
> Adding the v back to the elixir version fixed this for us @paulo-ferraz-oliveira , thank you

You can check the behaviour here: https://github.com/erlef/setup-beam/runs/3021625662?check_suite_focus=true#step:3:3

**Comment by paulo-ferraz-oliveira** [comment]
Hey, @vanvoljg. Your issue does seem similar, but I'll have to test further. You shouldn't need the `strict`, in your case, though. And if you do use it, you need a `v` in the Elixir version.

**Comment by vanvoljg** [comment]
> You shouldn't need the strict, in your case, though. And if you do use it, you need a v in the Elixir version.

I wondered if it would be required, but tested just in case. Thanks for the clarification!

If it helps you, I got the exact same error both with and without `strict` version type.

**Comment by paulo-ferraz-oliveira** [comment]
> > You shouldn't need the strict, in your case, though. And if you do use it, you need a v in the Elixir version.
> 
> I wondered if it would be required, but tested just in case. Thanks for the clarification!
> 
> If it helps you, I got the exact same error both with and without `strict` version type.

Can you add a `v` and check if that helps? (won't be the best solution, though - I'm working on it)

**Comment by vanvoljg** [comment]
@paulo-ferraz-oliveira I added it and, unfortunately, it returns the same error.

Also realized I omitted a step in the config I mentioned. I don't know if will matter, but `- uses: actions/checkout@v2` is also in there.

```yml
env:
  MIX_ENV: test
  OTP_VERSION_SPEC: "24.0.2"
  ELIXIR_VERSION_SPEC: "1.12.1"

jobs:
  compile:
    name: Compile
    steps:
      - uses: actions/checkout@v2
      - uses: erlef/setup-beam@v1
        id: setup
        with:
          otp-version: ${{ env.OTP_VERSION_SPEC }}
          elixir-version: ${{ env.ELIXIR_VERSION_SPEC }}
          version-type: "strict"
```
