### ISSUE TITLE
Action incompatible with self-hosted runners

### ISSUE THREAD

**Issue by IamBlueSlime** [erlef/setup-beam#58]
Hi,

This action is now incompatible with self-hosted runners, where the `ImageOS` environment variable is not provided. To let it work, the environment variable has to be injected manually:

```yaml
      - uses: erlef/setup-beam@v1
        with:
          otp-version: ${{ env.TARGET_ERLANG_VERSION }}
          elixir-version: ${{ env.TARGET_ELIXIR_VERSION }}
        env:
          # See:
          # https://github.com/erlef/setup-beam/blob/master/src/setup-beam.js#L340
          ImageOS: ubuntu20
```

Honestly, I do not know what to think about this 😞 , maybe you should rework this part by asking the system directly the version with `uname` maybe :).

**Comment by paulo-ferraz-oliveira** [comment]
Hi, @IamBlueSlime.

Was this working until recently but suddenly stopped working?

**Comment by IamBlueSlime** [comment]
> Hi, @IamBlueSlime.
> 
> Was this working until recently but suddenly stopped working?

Hi! Exactly, it stopped working since v1.8.0. I decided to pin the v1.7.2 in my workflows rather than using this tweak, personal preference.

**Comment by IamBlueSlime** [comment]
After investigating the diff, I'm pretty confident by saying that removing the fallback value here cause the issue, see `https://github.com/erlef/setup-beam/compare/v1.7.2...v1.8#diff-6406ae11684199b17d2cdca1efe2cfa29fb4587c3b142f1d33ad5f81a5acf7adL250`. The OTP download URL contains `undefined` in its path, the result of dereferencing an array with undefined.

**Comment by paulo-ferraz-oliveira** [comment]
The code to "guess" this, before, was

```
return mapToUbuntuVersion[process.env.ImageOS] || 'ubuntu-18.04'
```

now changed to

```
return mapToUbuntuVersion[process.env.ImageOS]
```

(since we now support Windows too)

but:

1. it gets easily outdated (20.04 is out, for example),
2. we're randomly guessing `ubuntu-18.04` (what if it's a self-hosted Windows runner?)

I don't mind restoring the `ubuntu-18.04` and keep previous behaviour, but it'll be a time bomb.

On the other hand, I could try as you propose `uname` but it'd have to work for Windows also, and macOS soon.

Let's wait on other maintainers to give their opinion on whether we should use the `env` or not.

**Comment by paulo-ferraz-oliveira** [comment]
> After investigating the diff, I'm pretty confident by saying that removing the fallback value here cause the issue, see [v1.7.2...v1.8.0diff-6406ae11684199b17d2cdca1efe2cfa29fb4587c3b142f1d33ad5f81a5acf7adR332](https://github.com/erlef/setup-beam/compare/v1.7.2...v1.8.0diff-6406ae11684199b17d2cdca1efe2cfa29fb4587c3b142f1d33ad5f81a5acf7adR332)
> 
> The OTP download URL contains `undefined` in its path, the result of dereferencing an array with undefined.

This link doesn't work for me.

**Comment by paulo-ferraz-oliveira** [comment]
Well, actually let me check if it's possible to have a default env. (where we'd inject the 18.04, for the time being).

**Comment by IamBlueSlime** [comment]
Restoring the default value is clearly not an option here, as you said it is a time bomb. You can read the following file `/etc/os-release` for Ubuntu:

```bash
$ cat /etc/os-release
NAME="Ubuntu"
VERSION="20.10 (Groovy Gorilla)"
ID=ubuntu
ID_LIKE=debian
PRETTY_NAME="Ubuntu 20.10"
VERSION_ID="20.10"
HOME_URL="https://www.ubuntu.com/"
SUPPORT_URL="https://help.ubuntu.com/"
BUG_REPORT_URL="https://bugs.launchpad.net/ubuntu/"
PRIVACY_POLICY_URL="https://www.ubuntu.com/legal/terms-and-policies/privacy-policy"
VERSION_CODENAME=groovy
UBUNTU_CODENAME=groovy
```

I suggest you to:
1. Check if `ImageOS` is present in the environment, then use it
2. Check if `process.platform` is Linux then try to read the file above
3. Otherwise, throw an error

Still not perfect, but better than nothing :)

**Comment by paulo-ferraz-oliveira** [comment]
> Check if process.platform is Linux then try to read the file above

That'd put a block on Windows self-hosted, right? I'm not sure we want that.

**Comment by paulo-ferraz-oliveira** [comment]
I think a workable course of action would be to test env. for that var. and if not present throw directly (listing the possible values). That way it's up to the consumer to decide.

**Comment by IamBlueSlime** [comment]
I do not have a Windows machine nearby, but there should be something more-or-less equivalent I guess. Meanwhile, it will be a good compromise don't you think?

**Comment by paulo-ferraz-oliveira** [comment]
I'll look at this in the evening, if I have time, because I need to think about Windows too. It should be considered a bug and not a purposeful breaking change, so expect 1.8.2. In the meantime, yeah, you'll have to pin.

**Comment by paulo-ferraz-oliveira** [comment]
> Meanwhile, it will be a good compromise don't you think?

What will? The compromise, for me, at the moment, is to pin the version to 1.7 until there's a fix. We added this info. to the README in the latest release, so consumers should (even if VERY unexpected) not rely on a moving tag.

**Comment by paulo-ferraz-oliveira** [comment]
Leaving this here for future reference (this evening hopefully, for me).

```
$ cat /etc/issue | head -n1 | awk '{print $2}' | awk -F. '{print "ubuntu-"$1"."$2}'
ubuntu-20.04
```

(works for Ubuntu 16.04, 18.04 and 20.04)

**Comment by paulo-ferraz-oliveira** [comment]
#59 was created to address this issue (hopefully it solves the reported bug). We try to guess the version as best as possible, especially for the containers we support (Ubuntu and Windows - made explicit in the README). If we can't do that, we exit with an explicit error (and you'll have to use `ImageOS`, in that case). Exceptions to this might require further external collaboration/pull requests.

**Comment by ericmj** [comment]
I don't know how self-hosted runners work but shouldn't they replicate the environment of hosted runners as closely as possible? It is impossible for us to test against every possible self-hosted runner, we can only reasonably test against the runners GitHub provides.

If other runners deviate so they no longer work I think it is up to the runner maintainers to fix it on their end and add the `ImageOS` env var.

**Comment by starbelly** [comment]
> If other runners deviate so they no longer work I think it is up to the runner maintainers to fix it on their end and add the `ImageOS` env var.

I whole heartily agree with this. I'd rather us not start doing guess work around operating systems when it's quite easy to specify the os. We have to keep in mind that we'll be supporting mac os and other *BSDs as well, in addition to linux distros and windows.

**Comment by ericmj** [comment]
> Maybe it's counter-intuitive for some cases of self-hosted runners to specify ImageOS per a self-hosted runner perhaps not even using docker or the like. If that's the case, we could support an alternative variable name. I think that's as far as I'd be willing to go myself though.

I agree, we should document `ImageOS` or perhaps another setting that you can set to select the OS that OTP was precompiled on. We can also point you in this direction in the error message if `ImageOS` was not set. Does that sound good @IamBlueSlime @paulo-ferraz-oliveira?

**Comment by paulo-ferraz-oliveira** [comment]
@ericmj, #59 introduces changes to `README.md`, and states needs for `ImageOS` in the error message, to make sure the consumer knows where to look when we can't guess properly.

We still try guess the _container_ though (that's #59, basically), and test for some of the runners GitHub provides. As this is a fallback I guess it's acceptable.

**Comment by bryannaegele** [comment]
This does not seem to be working properly with act.

https://github.com/nektos/act

```
[Elixir Unit Tests/Test on Elixir 1.11.4 (OTP 21.3.8.24) and ubuntu-18.04-7]   ❌  Failure - erlef/setup-beam@v1
[Elixir Unit Tests/Test on Elixir 1.12.2 (OTP 22.3.4.20) and ubuntu-18.04-5]   ❗  ::error::Tried to map a target OS from env. variable 'ImageOS', but failed. If you're using a self-hosted runner, you should set 'env': 'ImageOS': ... to one of the following: ['ubuntu16', 'ubuntu18', 'ubuntu20', 'win16', 'win19']
[Elixir Unit Tests/Test on Elixir 1.12.2 (OTP 22.3.4.20) and ubuntu-18.04-5]   ❌  Failure - erlef/setup-beam@v1
Error: exit with `FAILURE`: 1
```

```
name: Elixir Unit Tests

on:
  pull_request:
    branches:
      - 'main'
  push:
    branches:
      - 'main'

jobs:
  tests:
    runs-on: ${{ matrix.os }}
    name: Test on Elixir ${{ matrix.elixir_version }} (OTP ${{ matrix.otp_version }}) and ${{ matrix.os }}
    strategy:
      matrix:
        otp_version: ['24.0.4', '23.3.4.2', '22.3.4.20']
        elixir_version: ['1.12.2', '1.11.4']
        rebar3_version: ['3.16.1']
        os: [ubuntu-18.04]
        app: |
          instrumentation/opentelemetry_phoenix
        include:
          - otp_version: '21.3.8.24'
            elixir_version: '1.11.4'
            rebar3_version: '3.15.2'
            os: ubuntu-18.04
        exclude:
          - otp_version: '21.3.8.24'
            elixir_version: '1.12.2'
    env:
      OTP_VERSION: ${{ matrix.otp_version }}
      ELIXIR_VERSION: ${{ matrix.elixir_version }}
      ImageOS: ubuntu18
    steps:
      - uses: actions/checkout@v2
      - uses: erlef/setup-beam@v1
        with:
          otp-version: ${{ matrix.otp_version }}
          elixir-version: ${{ matrix.elixir_version }}
          rebar3-version: ${{ matrix.rebar3_version }}
      - uses: actions/cache@v2
        name: Cache
        with:
          path: |
            ${{ matrix.app }}/deps
            ${{ matrix.app }}/_build
          key: ${{ runner.os }}-build-${{ matrix.otp_version }}-${{ matrix.elixir_version }}-v3-${{ hashFiles(format('{0}{1}', github.workspace, '/${{ matrix.app }}/mix.lock')) }}
          restore-keys: |
            ${{ runner.os }}-build-${{ matrix.otp_version }}-${{ matrix.elixir_version }}-
      - run: mix deps.get
        working-directory: ${{ matrix.app }}
        name: Deps
      - run: mix test --warnings-as-errors
        working-directory: ${{ matrix.app }}
        name: Test
 ```
