### ISSUE TITLE
Dependency failing to compile in 1.8.x

### ISSUE THREAD

**Issue by tomasz-tomczyk** [erlef/setup-beam#66]
Hi, our CI started failing last night - we were pointed at the action `setup-elixir@v1`; the error was as follows:

```
Cannot read file '/home/runner/work/_temp/.setup-beam/otp/lib/public_key-1.10/include/public_key.hrl': no such file or directory
** (Mix) Could not compile dependency :esaml, "/home/runner/.mix/rebar3 bare compile --paths 

/home/runner/work/api/_build/test/lib/*/ebin" command failed. You can recompile this dependency with "mix deps.compile esaml", update it with "mix deps.update esaml" or clean it with "mix deps.clean esaml"
```

This persisted as we switched to `setup-beam@v1.8.0` and latest `1.8.3`

**Current workaround:** The error went away when we dropped to `setup-beam@v1.7.2`

Workflow excerpt:

```
jobs:
  api-test:
    env:
      ELIXIR_VERSION: 1.11.1
      OTP_VERSION: 23.0
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: postgres
    name: API | test & lint [pr]
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@master
      - name: Start Database
        run: docker-compose up -d db
      - name: Setup the container with elixir, erlang and OTP
        uses: erlef/setup-beam@v1.8.3
        with:
          otp-version: ${{ env.OTP_VERSION }}
          elixir-version: ${{ env.ELIXIR_VERSION }}
      - uses: actions/cache@v2
        with:
          path: |
            api/deps
            api/_build
          key: ${{ runner.os }}-dependencies-${{ hashFiles('mix.lock') }}-${{ env.ELIXIR_VERSION }}-${{ env.OTP_VERSION }}
          restore-keys: |
            ${{ runner.os }}-dependencies-${{ hashFiles('mix.lock') }}-${{ env.ELIXIR_VERSION }}-${{ env.OTP_VERSION }}
            ${{ runner.os }}-dependencies-${{ hashFiles('mix.lock') }}-${{ env.ELIXIR_VERSION }}-
            ${{ runner.os }}-dependencies-${{ hashFiles('mix.lock') }}-
            ${{ runner.os }}-dependencies-
      - name: Get mix dependencies
        run: mix deps.get
        working-directory: ./api
      - name: Compile Deps
        run: MIX_ENV=test mix deps.compile
        working-directory: ./api
      - name: Compile
        run: MIX_ENV=test mix compile --warnings-as-errors --force
        working-directory: ./api
      - name: Check format
        run: MIX_ENV=test mix format "lib/**/*.{ex,exs}" --check-formatted
        working-directory: ./api
      - name: Credo
        run: MIX_ENV=test mix credo
        working-directory: ./api
      - name: Run tests
        run: MIX_ENV=test mix test
        working-directory: ./api
```

The dependency in question was [esaml](https://github.com/handnot2/esaml) brought in by [samly](https://github.com/handnot2/samly), which I appreciate hasn't been worked on for a while, but thought I'd see if anyone here has any ideas on a better fix as obviously we don't want to be tied to an older GH action version

Updating to OTP 24 was giving another issue at the same step:

```
escript: exception error: undefined function erlang:get_stacktrace/0
```

Thanks for any help!
