### ISSUE TITLE
Elixir Master opens interactive terminal

### ISSUE THREAD

**Issue by samhamilton** [erlef/setup-beam#70]
Hi, 

When trying to test elixir master branch via the below code, the action opens an interactive terminal and will not move to the next step, I have had a quick scan of the docs and didn't spot anything that might disable when running a branch rather than a release so guessing this is a bug?

```
- uses: erlef/setup-beam@v1.8.3
        with:
          otp-version: "24.x"
          elixir-version: "master"
```

<img width="798" alt="Screenshot 2021-08-19 at 18 21 14" src="https://user-images.githubusercontent.com/415410/130052900-ea4c684d-6b66-4f22-afdc-13e4e80b5e80.png">

Thanks
Sam
