### ISSUE TITLE
ct_run

### ISSUE THREAD

**Issue by ostinelli** [erlef/setup-beam#72]
Hello,
I'm trying to run `ct_run` instead of `rebar3` as I need additional features not available in rebar, and following recommendations as per https://rebar3.readme.io/docs/running-tests.

I have:

```yml
on:
  pull_request:
    branches:
      - "main"
  push:
    branches:
      - "v3"

jobs:
  test:
    runs-on: ubuntu-latest
    name: Tests on ${{matrix.otp}}
    strategy:
      matrix:
        otp: ['24.0']
    steps:
      - uses: actions/checkout@v2
      - uses: erlef/setup-beam@v1
        with:
          otp-version: ${{matrix.otp}}
          rebar3-version: 3.17.0
      - name: Compile
        run: rebar3 as test compile
      - name: Common Test tests
        run: ct_run -dir ./test -pa `rebar3 as test path`
```

I get:

```
Run rebar3 as test compile
  rebar3 as test compile
  shell: /usr/bin/bash -e {0}
===> Verifying dependencies...
===> Analyzing applications...
===> Compiling my_app
```

But the tests themselves show:

```
Run ct_run -dir ./test -pa `rebar3 as test path`
  ct_run -dir ./test -pa `rebar3 as test path`
  shell: /usr/bin/bash -e {0}

Eshell V12.0.4  (abort with ^G)
(ct@fv-az131-258)1> *** Terminating erlang ('ct@fv-az131-258')
```

This returns a green result but tests are never run.

Can someone please give me a pointer on what I might be doing wrong?

Thank you,
r.
