### ISSUE TITLE
No Rebar configured, but I get a Rebar Warning: 'Authenticity is not established by certificate path validation'

### ISSUE THREAD

**Issue by mezz** [erlef/setup-beam#73]
Hello,
I am creating some Github Actions using `setup-beam`.
I use `mix` and don't need `rebar`, but it looks like `setup-beam` is calling `rebar` and I get a warning:

> /home/runner/work/_temp/.setup-beam/elixir/bin/mix local.rebar --force
>
>  21:00:50.196 [warn]  Description: 'Authenticity is not established by certificate path validation'
>  Warning:      Reason: 'Option {verify, verify_peer} and cacertfile/cacerts is missing'

My github action configuration looks like this:
```yaml
jobs:
  build:
    name: Build and test
    runs-on: ubuntu-latest
    strategy:
      matrix:
        include:
          - elixir-version: 1.12.3
            otp-version: 23.3
          - elixir-version: 1.12.3
            otp-version: 24.1

    env:
      MIX_ENV: test

    steps:
    - uses: actions/checkout@v2
    
    - name: Set up Elixir
      uses: erlef/setup-beam@v1.9.0
      with:
        elixir-version: ${{ matrix.elixir-version }}
        otp-version: ${{ matrix.otp-version }}

    - name: Restore dependencies cache
      uses: actions/cache@v2
      with:
        path: deps
        key: ${{ runner.os }}-${{ matrix.elixir-version }}-${{ matrix.otp-version }}-mix-${{ hashFiles('**/mix.lock') }}
        restore-keys: ${{ runner.os }}-${{ matrix.elixir-version }}-${{ matrix.otp-version }}-mix-

    - name: Install dependencies
      run: mix deps.get

    - name: Compile code
      run: mix compile --warnings-as-errors

    - name: Run tests
      run: mix test
```

I tried looking into the source a bit here, but I'm not exactly sure why it's calling `rebar` at all since I didn't specify a version for it.
Thank you for the `setup-beam` action!
