### ISSUE TITLE
Setting elixir version to 1.10 results in setup-beam trying to install 1.1

### ISSUE THREAD

**Issue by mezz** [erlef/setup-beam#74]
I think there is an issue with version parsing for versions that end in 0.

```yaml
- name: Set up Elixir
      uses: erlef/setup-beam@v1.9.0
      with:
        elixir-version: 1.10
        otp-version: 21
```
results in installing Elixir `1.1`

I can work around the issue by puttin quotes around `1.10`:
```yaml
- name: Set up Elixir
      uses: erlef/setup-beam@v1.9.0
      with:
        elixir-version: "1.10"
        otp-version: 21
```
results in installing Elixir `1.10` correctly
