### ISSUE TITLE
Cache OTP environment

### ISSUE THREAD

**Issue by onelesd** [erlef/setup-beam#80]
Is it possible to cache the setup of the environment with something like below?

Sometimes this step fails after 60 seconds because hex.pm times out. This could reduce the load on hex.pm and save build time. 

```
...
      - name: Retrieve cached dependencies
        uses: actions/cache@v2
        id: erlang
        with:
          path: deps
          key: ${{ runner.os }}-${{ matrix.otp }}-${{ matrix.elixir }}
      - name: Sets up an Erlang/OTP environment
        if: steps.erlang.outputs.cache-hit != 'true'
        uses: erlef/setup-beam@v1
        with:
          elixir-version: ${{ matrix.elixir }}
          otp-version: ${{ matrix.otp }}
...

```
